import type { Program } from '@/types/database';

export const SEED_PROGRAMS: Omit<Program, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    external_id: 'sf-basic-2026',
    source: 'manual',
    title: '스마트공장 기초 구축 지원사업',
    managing_org: '중소벤처기업부',
    implementing_org: '스마트제조혁신추진단',
    category: '경영',
    subcategory: '스마트공장',
    support_type: '보조금',
    target_industries: ['제조업'],
    target_regions: ['전국'],
    target_company_size: ['소기업', '소상공인'],
    min_employee_count: null,
    max_employee_count: 50,
    min_revenue: null,
    max_revenue: 10000000000,
    min_company_age: 1,
    max_company_age: null,
    funding_amount_min: 30000000,
    funding_amount_max: 50000000,
    self_funding_ratio: 30,
    application_start: '2026-03-01',
    application_end: '2026-04-30',
    status: 'open',
    description: '제조 중소기업의 스마트공장 기초 단계 구축을 지원합니다. MES(생산관리시스템), IoT 센서, 공정 자동화 장비 등 도입 비용을 지원하며, 자부담 30%가 필요합니다. 선정 후 6개월 이내 구축 완료, 3년간 사후관리를 받게 됩니다.',
    eligibility_summary: '제조업 영위 중소기업, 직원 50인 이하, 매출 100억 이하, 업력 1년 이상',
    required_documents: ['사업계획서', '사업자등록증', '재무제표(최근 2년)', '견적서', '공장등록증', '4대보험 가입증명서'],
    detail_url: 'https://www.smart-factory.kr',
    is_featured: true,
    last_synced_at: null,
  },
  {
    external_id: 'sf-advanced-2026',
    source: 'manual',
    title: '스마트공장 고도화 지원사업',
    managing_org: '중소벤처기업부',
    implementing_org: '스마트제조혁신추진단',
    category: '경영',
    subcategory: '스마트공장',
    support_type: '보조금',
    target_industries: ['제조업'],
    target_regions: ['전국'],
    target_company_size: ['소기업', '중기업'],
    min_employee_count: null,
    max_employee_count: 300,
    min_revenue: null,
    max_revenue: 50000000000,
    min_company_age: 3,
    max_company_age: null,
    funding_amount_min: 100000000,
    funding_amount_max: 300000000,
    self_funding_ratio: 50,
    application_start: '2026-03-01',
    application_end: '2026-05-31',
    status: 'open',
    description: '기초 스마트공장 구축 완료 기업을 대상으로 AI·빅데이터 기반 고도화 수준(Level 3~4)으로 업그레이드를 지원합니다. 데이터 수집·분석, AI 품질검사, 에너지 관리 시스템 등을 지원합니다.',
    eligibility_summary: '제조업 중소·중견기업, 스마트공장 기초 구축 완료 기업 우대, 업력 3년 이상',
    required_documents: ['사업계획서', '사업자등록증', '재무제표(최근 3년)', '기존 스마트공장 구축 확인서', '견적서', '기술개발계획서'],
    detail_url: 'https://www.smart-factory.kr',
    is_featured: true,
    last_synced_at: null,
  },
  {
    external_id: 'sme-loan-direct-2026',
    source: 'manual',
    title: '소상공인 정책자금 직접대출',
    managing_org: '중소벤처기업부',
    implementing_org: '소상공인시장진흥공단',
    category: '금융',
    subcategory: '정책자금',
    support_type: '융자',
    target_industries: [],
    target_regions: ['전국'],
    target_company_size: ['소상공인'],
    min_employee_count: null,
    max_employee_count: 5,
    min_revenue: null,
    max_revenue: 1200000000,
    min_company_age: null,
    max_company_age: null,
    funding_amount_min: 10000000,
    funding_amount_max: 70000000,
    self_funding_ratio: null,
    application_start: '2026-01-02',
    application_end: '2026-12-31',
    status: 'open',
    description: '소상공인을 대상으로 저금리(연 2~3%) 정책자금을 직접 대출합니다. 경영안정, 창업, 재도전, 성장촉진 등 다양한 용도로 활용 가능하며 최대 7,000만원까지 지원됩니다.',
    eligibility_summary: '업종별 소상공인 기준 충족(직원 5인 미만, 숙박·음식점업은 10인 미만), 연매출 12억 이하',
    required_documents: ['사업자등록증', '신분증', '임대차계약서', '매출확인서류', '부채증명원'],
    detail_url: 'https://ols.sbiz.or.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'sme-emergency-2026',
    source: 'manual',
    title: '중소기업 긴급경영안정자금',
    managing_org: '중소벤처기업부',
    implementing_org: '중소벤처기업진흥공단',
    category: '금융',
    subcategory: '긴급자금',
    support_type: '융자',
    target_industries: [],
    target_regions: ['전국'],
    target_company_size: ['소기업', '중기업', '소상공인'],
    min_employee_count: null,
    max_employee_count: 300,
    min_revenue: null,
    max_revenue: null,
    min_company_age: null,
    max_company_age: null,
    funding_amount_min: 50000000,
    funding_amount_max: 1000000000,
    self_funding_ratio: null,
    application_start: '2026-01-02',
    application_end: '2026-12-31',
    status: 'open',
    description: '경기침체, 재해, 수출 급감 등으로 경영 위기에 처한 중소기업에 긴급 운전자금을 지원합니다. 연 2.4%~3.2% 저금리로 최대 10억원까지 융자 가능합니다.',
    eligibility_summary: '중소기업기본법상 중소기업, 최근 매출 감소 20% 이상 또는 재해 피해 기업',
    required_documents: ['사업자등록증', '재무제표', '매출감소 확인서류', '경영위기 증빙서류', '담보제공서류(해당시)'],
    detail_url: 'https://www.kosmes.or.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'export-voucher-2026',
    source: 'manual',
    title: '수출바우처 지원사업',
    managing_org: '산업통상자원부',
    implementing_org: '한국무역협회·KOTRA',
    category: '수출',
    subcategory: '수출지원',
    support_type: '바우처',
    target_industries: [],
    target_regions: ['전국'],
    target_company_size: ['소기업', '중기업'],
    min_employee_count: null,
    max_employee_count: 300,
    min_revenue: null,
    max_revenue: 100000000000,
    min_company_age: 1,
    max_company_age: null,
    funding_amount_min: 10000000,
    funding_amount_max: 100000000,
    self_funding_ratio: 30,
    application_start: '2026-02-01',
    application_end: '2026-04-15',
    status: 'open',
    description: '수출 역량을 갖춘 중소·중견기업에 해외시장 조사, 브랜딩, 마케팅, 전시회 참가 등 수출 관련 비용을 바우처로 지원합니다. 자부담 30%, 정부지원 70%입니다.',
    eligibility_summary: '수출 실적 또는 수출 의지가 있는 중소기업, 업력 1년 이상',
    required_documents: ['사업자등록증', '수출실적증명서(해당시)', '사업계획서', '재무제표', '수출계획서'],
    detail_url: 'https://www.exportvoucher.com',
    is_featured: true,
    last_synced_at: null,
  },
  {
    external_id: 'rd-sme-2026',
    source: 'manual',
    title: '중소기업 기술개발(R&D) 지원사업',
    managing_org: '중소벤처기업부',
    implementing_org: '중소기업기술정보진흥원(TIPA)',
    category: '기술',
    subcategory: 'R&D',
    support_type: '보조금',
    target_industries: [],
    target_regions: ['전국'],
    target_company_size: ['소기업', '중기업'],
    min_employee_count: null,
    max_employee_count: 300,
    min_revenue: null,
    max_revenue: null,
    min_company_age: 1,
    max_company_age: null,
    funding_amount_min: 50000000,
    funding_amount_max: 500000000,
    self_funding_ratio: 20,
    application_start: '2026-03-15',
    application_end: '2026-04-30',
    status: 'open',
    description: '기술 혁신 의지가 있는 중소기업의 신제품·신기술 개발을 지원합니다. 창업성장, 전략품목, 글로벌 등 다양한 트랙이 있으며 과제 규모에 따라 지원금이 다릅니다.',
    eligibility_summary: '중소기업, 기술 개발 의지 및 역량 보유, 업력 1년 이상, 기업부설연구소 또는 연구전담부서 보유 우대',
    required_documents: ['사업계획서', '기술개발계획서', '사업자등록증', '재무제표', '연구소 인정서(해당시)', '연구원 재직증명서'],
    detail_url: 'https://www.smtech.go.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'youth-employment-2026',
    source: 'manual',
    title: '청년고용장려금',
    managing_org: '고용노동부',
    implementing_org: '고용센터',
    category: '인력',
    subcategory: '고용지원',
    support_type: '보조금',
    target_industries: [],
    target_regions: ['전국'],
    target_company_size: ['소상공인', '소기업', '중기업'],
    min_employee_count: null,
    max_employee_count: 500,
    min_revenue: null,
    max_revenue: null,
    min_company_age: null,
    max_company_age: null,
    funding_amount_min: 9600000,
    funding_amount_max: 9600000,
    self_funding_ratio: null,
    application_start: '2026-01-02',
    application_end: '2026-12-31',
    status: 'open',
    description: '청년(15~34세)을 정규직으로 채용한 중소·중견기업에 1인당 최대 960만원(월 80만원×12개월)을 지원합니다. 신규 채용 청년 1인당 지원이 가능합니다.',
    eligibility_summary: '청년(15~34세) 신규 정규직 채용 기업, 직전 3개월 이상 고용보험 가입 사업장',
    required_documents: ['사업자등록증', '4대보험 사업장가입자 명부', '근로계약서', '청년 주민등록증 사본'],
    detail_url: 'https://www.work.go.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'naeiljaeumgongje-2026',
    source: 'manual',
    title: '내일채움공제 (핵심인력 성과보상기금)',
    managing_org: '중소벤처기업부',
    implementing_org: '중소벤처기업진흥공단',
    category: '인력',
    subcategory: '핵심인력',
    support_type: '매칭',
    target_industries: [],
    target_regions: ['전국'],
    target_company_size: ['소기업', '중기업'],
    min_employee_count: null,
    max_employee_count: 300,
    min_revenue: null,
    max_revenue: null,
    min_company_age: null,
    max_company_age: null,
    funding_amount_min: 12000000,
    funding_amount_max: 20000000,
    self_funding_ratio: 50,
    application_start: '2026-01-02',
    application_end: '2026-12-31',
    status: 'open',
    description: '핵심인력의 장기 재직을 위해 기업과 핵심인력이 공동으로 적립하면 정부가 매칭 지원합니다. 5년 만기 시 핵심인력이 2,000~3,000만원 수령 가능합니다.',
    eligibility_summary: '중소기업 재직 핵심인력, 6개월 이상 재직, 사업주와 공동 납입 합의',
    required_documents: ['사업자등록증', '핵심인력 재직증명서', '근로계약서', '4대보험 취득확인서'],
    detail_url: 'https://www.sbcplan.or.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'sogongin-special-2026',
    source: 'manual',
    title: '소공인 특화 지원사업 (집적지 육성)',
    managing_org: '중소벤처기업부',
    implementing_org: '소상공인시장진흥공단',
    category: '경영',
    subcategory: '소공인',
    support_type: '보조금',
    target_industries: ['제조업'],
    target_regions: ['전국'],
    target_company_size: ['소상공인'],
    min_employee_count: null,
    max_employee_count: 10,
    min_revenue: null,
    max_revenue: null,
    min_company_age: 1,
    max_company_age: null,
    funding_amount_min: 5000000,
    funding_amount_max: 30000000,
    self_funding_ratio: 20,
    application_start: '2026-03-01',
    application_end: '2026-04-30',
    status: 'open',
    description: '소공인(10인 미만 제조업) 집적지를 중심으로 공동장비, 공동브랜드, 마케팅, 기술지원 등을 패키지로 지원합니다.',
    eligibility_summary: '제조업 소공인(상시근로자 10인 미만), 소공인 특화지원센터 인근 위치 우대',
    required_documents: ['사업자등록증', '제조업 확인서류', '사업계획서', '재무제표', '공장임대차계약서'],
    detail_url: 'https://www.sbiz.or.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'local-industry-2026',
    source: 'manual',
    title: '지역특화산업 육성사업',
    managing_org: '산업통상자원부',
    implementing_org: '각 지역 테크노파크',
    category: '기술',
    subcategory: '지역특화',
    support_type: '보조금',
    target_industries: [],
    target_regions: ['충청북도', '경상북도', '전라남도', '강원특별자치도', '경상남도'],
    target_company_size: ['소기업', '중기업'],
    min_employee_count: null,
    max_employee_count: 300,
    min_revenue: null,
    max_revenue: null,
    min_company_age: 1,
    max_company_age: null,
    funding_amount_min: 50000000,
    funding_amount_max: 200000000,
    self_funding_ratio: 20,
    application_start: '2026-04-01',
    application_end: '2026-05-31',
    status: 'upcoming',
    description: '각 지역의 특화산업(충북 바이오, 경북 IT, 전남 에너지 등)과 연계한 기업의 기술개발 및 사업화를 지원합니다. 지역 테크노파크를 통해 신청하세요.',
    eligibility_summary: '해당 지역 소재 중소기업, 지역 특화산업 분야 영위, 업력 1년 이상',
    required_documents: ['사업자등록증', '사업계획서', '기술개발계획서', '재무제표', '지역 소재 확인서류'],
    detail_url: 'https://www.technopark.or.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'digital-transform-2026',
    source: 'manual',
    title: '중소기업 디지털 전환 지원사업',
    managing_org: '중소벤처기업부',
    implementing_org: '중소기업기술정보진흥원',
    category: '경영',
    subcategory: '디지털전환',
    support_type: '바우처',
    target_industries: [],
    target_regions: ['전국'],
    target_company_size: ['소기업', '중기업', '소상공인'],
    min_employee_count: null,
    max_employee_count: 300,
    min_revenue: null,
    max_revenue: null,
    min_company_age: 1,
    max_company_age: null,
    funding_amount_min: 10000000,
    funding_amount_max: 30000000,
    self_funding_ratio: 30,
    application_start: '2026-02-15',
    application_end: '2026-04-30',
    status: 'open',
    description: '클라우드, AI, 빅데이터 등 디지털 기술을 활용한 업무 프로세스 혁신을 지원합니다. ERP, CRM, 온라인 쇼핑몰 구축, 디지털 마케팅 도구 등을 바우처로 구매 가능합니다.',
    eligibility_summary: '중소기업 및 소상공인, 디지털 전환 의지 및 계획 보유, 업력 1년 이상',
    required_documents: ['사업자등록증', '사업계획서(디지털전환)', '재무제표', '현재 업무프로세스 설명서'],
    detail_url: 'https://www.smtech.go.kr',
    is_featured: true,
    last_synced_at: null,
  },
  {
    external_id: 'agri-food-modern-2026',
    source: 'manual',
    title: '농식품 가공시설 현대화 지원',
    managing_org: '농림축산식품부',
    implementing_org: '농림수산식품교육문화정보원',
    category: '금융',
    subcategory: '농식품',
    support_type: '융자',
    target_industries: ['농업·임업·어업', '제조업'],
    target_regions: ['전국'],
    target_company_size: ['소기업', '소상공인'],
    min_employee_count: null,
    max_employee_count: 50,
    min_revenue: null,
    max_revenue: null,
    min_company_age: 1,
    max_company_age: null,
    funding_amount_min: 50000000,
    funding_amount_max: 300000000,
    self_funding_ratio: null,
    application_start: '2026-04-01',
    application_end: '2026-06-30',
    status: 'upcoming',
    description: '농식품 제조·가공업체의 시설 현대화, 위생·안전 시설 개선, 스마트화를 위한 저금리(연 2%) 융자를 지원합니다. 발효주·가공식품·전통식품 업체 적합.',
    eligibility_summary: '농식품 제조·가공업 영위 소기업, 식품제조업 허가 보유, 업력 1년 이상',
    required_documents: ['사업자등록증', '식품제조업 허가증', '사업계획서', '견적서', '재무제표', '공장등록증'],
    detail_url: 'https://www.mafra.go.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'trad-market-digital-2026',
    source: 'manual',
    title: '전통시장 디지털 전환 지원',
    managing_org: '중소벤처기업부',
    implementing_org: '소상공인시장진흥공단',
    category: '내수',
    subcategory: '전통시장',
    support_type: '보조금',
    target_industries: ['도소매업', '음식점업'],
    target_regions: ['전국'],
    target_company_size: ['소상공인'],
    min_employee_count: null,
    max_employee_count: 5,
    min_revenue: null,
    max_revenue: null,
    min_company_age: null,
    max_company_age: null,
    funding_amount_min: 2000000,
    funding_amount_max: 10000000,
    self_funding_ratio: 20,
    application_start: '2026-03-01',
    application_end: '2026-05-31',
    status: 'open',
    description: '전통시장 및 상점가 내 소상공인의 온라인 판로 개척, SNS 마케팅, 키오스크 도입 등 디지털 전환을 지원합니다.',
    eligibility_summary: '전통시장 또는 상점가 내 소상공인, 사업자등록증 보유',
    required_documents: ['사업자등록증', '전통시장 입점 확인서', '사업계획서'],
    detail_url: 'https://www.sbiz.or.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'solo-creator-2026',
    source: 'manual',
    title: '1인 창조기업 지원사업',
    managing_org: '중소벤처기업부',
    implementing_org: '창조경제혁신센터',
    category: '창업',
    subcategory: '1인기업',
    support_type: '바우처',
    target_industries: ['정보통신업', '전문·과학·기술서비스업'],
    target_regions: ['전국'],
    target_company_size: ['소상공인'],
    min_employee_count: null,
    max_employee_count: 1,
    min_revenue: null,
    max_revenue: null,
    min_company_age: null,
    max_company_age: 7,
    funding_amount_min: 5000000,
    funding_amount_max: 20000000,
    self_funding_ratio: 20,
    application_start: '2026-03-15',
    application_end: '2026-04-30',
    status: 'open',
    description: '1인이 운영하는 창조기업에 마케팅, 법률·회계, 기술개발 등 비즈니스 지원 서비스를 바우처로 제공합니다.',
    eligibility_summary: '1인 창조기업(대표자 포함 상시근로자 5인 이하), 창업 7년 이내, 지식서비스업 해당',
    required_documents: ['사업자등록증', '1인창조기업확인서', '사업계획서'],
    detail_url: 'https://www.1jeop.or.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'women-biz-2026',
    source: 'manual',
    title: '여성기업 육성자금 지원',
    managing_org: '중소벤처기업부',
    implementing_org: '여성기업종합지원센터',
    category: '금융',
    subcategory: '여성기업',
    support_type: '융자',
    target_industries: [],
    target_regions: ['전국'],
    target_company_size: ['소기업', '중기업', '소상공인'],
    min_employee_count: null,
    max_employee_count: 300,
    min_revenue: null,
    max_revenue: null,
    min_company_age: null,
    max_company_age: null,
    funding_amount_min: 10000000,
    funding_amount_max: 100000000,
    self_funding_ratio: null,
    application_start: '2026-01-02',
    application_end: '2026-12-31',
    status: 'open',
    description: '여성이 대표자인 중소기업 및 소상공인에게 저금리 정책자금을 지원합니다. 연 2~3% 금리로 최대 1억원까지 지원 가능합니다.',
    eligibility_summary: '여성이 대표자인 중소기업 또는 소상공인, 여성기업확인서 보유 우대',
    required_documents: ['사업자등록증', '대표자 신분증', '재무제표', '여성기업확인서(해당시)'],
    detail_url: 'https://www.wbiz.or.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'mfg-voucher-2026',
    source: 'manual',
    title: '제조혁신 바우처 지원사업',
    managing_org: '산업통상자원부',
    implementing_org: '한국산업기술진흥원(KIAT)',
    category: '기술',
    subcategory: '제조혁신',
    support_type: '바우처',
    target_industries: ['제조업'],
    target_regions: ['전국'],
    target_company_size: ['소기업', '중기업'],
    min_employee_count: null,
    max_employee_count: 300,
    min_revenue: null,
    max_revenue: null,
    min_company_age: 1,
    max_company_age: null,
    funding_amount_min: 20000000,
    funding_amount_max: 100000000,
    self_funding_ratio: 30,
    application_start: '2026-03-01',
    application_end: '2026-04-15',
    status: 'open',
    description: '제조 중소기업의 공정 혁신, 품질 개선, 생산성 향상을 위한 설비·솔루션 구입비를 바우처로 지원합니다. KS인증, ISO 취득 지원도 포함됩니다.',
    eligibility_summary: '제조업 중소기업, 업력 1년 이상, 매출 500억 이하',
    required_documents: ['사업자등록증', '사업계획서', '재무제표', '견적서', '공장등록증'],
    detail_url: 'https://www.kiat.or.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'carbon-neutral-2026',
    source: 'manual',
    title: '탄소중립 설비전환 지원사업',
    managing_org: '산업통상자원부',
    implementing_org: '한국에너지공단',
    category: '기술',
    subcategory: '친환경',
    support_type: '보조금',
    target_industries: ['제조업'],
    target_regions: ['전국'],
    target_company_size: ['소기업', '중기업'],
    min_employee_count: null,
    max_employee_count: 300,
    min_revenue: null,
    max_revenue: null,
    min_company_age: 1,
    max_company_age: null,
    funding_amount_min: 50000000,
    funding_amount_max: 500000000,
    self_funding_ratio: 40,
    application_start: '2026-04-01',
    application_end: '2026-05-31',
    status: 'upcoming',
    description: '탄소 배출 감소를 위한 고효율 설비, 재생에너지 설비, 친환경 공정 도입 비용을 지원합니다. RE100 추진 기업 우대.',
    eligibility_summary: '제조업 중소기업, 탄소배출 감축 계획 제출, 에너지 진단 완료',
    required_documents: ['사업자등록증', '에너지진단보고서', '탄소감축계획서', '견적서', '재무제표'],
    detail_url: 'https://www.energy.or.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'indpark-support-2026',
    source: 'manual',
    title: '산업단지 입주기업 특별지원',
    managing_org: '산업통상자원부',
    implementing_org: '한국산업단지공단',
    category: '금융',
    subcategory: '산업단지',
    support_type: '융자',
    target_industries: ['제조업'],
    target_regions: ['전국'],
    target_company_size: ['소기업', '중기업'],
    min_employee_count: null,
    max_employee_count: 300,
    min_revenue: null,
    max_revenue: null,
    min_company_age: null,
    max_company_age: null,
    funding_amount_min: 100000000,
    funding_amount_max: 2000000000,
    self_funding_ratio: null,
    application_start: '2026-01-02',
    application_end: '2026-12-31',
    status: 'open',
    description: '산업단지 입주 기업에게 공장 증설, 설비 투자, 임차보증금 등에 대해 저금리 융자를 지원합니다. 산업단지 내 부지 매입에도 활용 가능합니다.',
    eligibility_summary: '국가·일반 산업단지 입주 중소기업, 산업단지 관리공단 확인서 보유',
    required_documents: ['산업단지 입주확인서', '사업자등록증', '재무제표', '사업계획서', '공장등록증'],
    detail_url: 'https://www.kicox.or.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'chungbuk-tp-2026',
    source: 'manual',
    title: '충북 테크노파크 중소기업 성장 지원',
    managing_org: '충청북도',
    implementing_org: '충북테크노파크',
    category: '기술',
    subcategory: '지역산업',
    support_type: '보조금',
    target_industries: ['제조업', '정보통신업'],
    target_regions: ['충청북도'],
    target_company_size: ['소기업', '중기업'],
    min_employee_count: null,
    max_employee_count: 300,
    min_revenue: null,
    max_revenue: null,
    min_company_age: 1,
    max_company_age: null,
    funding_amount_min: 20000000,
    funding_amount_max: 100000000,
    self_funding_ratio: 20,
    application_start: '2026-03-15',
    application_end: '2026-04-30',
    status: 'open',
    description: '충청북도 소재 중소기업의 기술개발, 판로개척, 스마트 제조화를 지원합니다. 충북TP 보유 장비 무상 활용, 전문가 컨설팅도 포함됩니다.',
    eligibility_summary: '충청북도 소재 중소기업, 업력 1년 이상, 제조업 또는 IT기업',
    required_documents: ['사업자등록증', '충북 소재 확인서류', '사업계획서', '재무제표'],
    detail_url: 'https://www.cbtp.or.kr',
    is_featured: false,
    last_synced_at: null,
  },
  {
    external_id: 'startup-tips-2026',
    source: 'manual',
    title: '민간투자주도형 기술창업 지원(TIPS)',
    managing_org: '중소벤처기업부',
    implementing_org: '중소기업기술정보진흥원',
    category: '창업',
    subcategory: '기술창업',
    support_type: '보조금',
    target_industries: [],
    target_regions: ['전국'],
    target_company_size: ['소기업'],
    min_employee_count: null,
    max_employee_count: 50,
    min_revenue: null,
    max_revenue: null,
    min_company_age: null,
    max_company_age: 7,
    funding_amount_min: 500000000,
    funding_amount_max: 1000000000,
    self_funding_ratio: 10,
    application_start: '2026-02-01',
    application_end: '2026-12-31',
    status: 'open',
    description: '엑셀러레이터(AC)가 선발·투자한 기술창업 기업에 정부가 R&D 자금, 해외진출, 창업사업화를 최대 10억원까지 지원합니다. AC의 추천이 필요합니다.',
    eligibility_summary: 'TIPS 운영사(엑셀러레이터)의 추천을 받은 기술 스타트업, 창업 7년 이내, 벤처기업 확인 우대',
    required_documents: ['TIPS운영사 추천서', '사업계획서', '사업자등록증', '기술성 증명서류', '팀구성원 이력서'],
    detail_url: 'https://www.jointips.or.kr',
    is_featured: false,
    last_synced_at: null,
  },
];
